- type: Tax Services
  description: Every year with new legislations the Congress adds numerous tax provisions to the already complex Internal Revenue Code. 
    Whether you are an Individual starting your career, having a corporation since years or nearing retirement you must be thoroughly aware 
    how complex our system of taxation is. It is virtually impossible for any individual or business to keep a track of all the new laws, 
    their implications, numerous tax planning opportunities to utilize or the tax pitfalls to avoid.
    We not only prepare your Individual, Corporation, Partnerships, LLCs, Trust, Pension, Estate tax return, but also work with you round 
    the year and look for every opportunity to save your hard earned dollar.
    Additionally we also have interim planning sessions where we update ourselves of the developments in your business and accordingly 
    plan the tax incentives available to you at various levels.
  image: /assets/img/tax_service.jpg

- type: Accounting Services
  description: K. K. Mehta CPA Associates PLLC performs a broad range of accounting services encompassing Bookkeeping, Payroll, Sales Tax, 
    reviews, Unaudited / Compilation Financial Statements, financial forecasts and projections, and agreed-upon procedures. In the course 
    of our services we obtain information that enables us to identify internal control risks and potential business problems and to 
    provide sound advice on financial management.
    The accounting team consists of knowledgeable and dedicated professionals who are committed to providing objective, meaningful 
    and efficient services. We also provide monthly or quarterly financials as per the client’s requirements to keep them abreast of 
    their situation.
  image: /assets/img/accounting_service.jpg

- type: Retirement Planning
  description: A very important avenue for future financial security is retirement planning. Contributions for the pension plan may 
    be as high as a few hundred thousand dollars. Based on each individual situation, we suggest various pension plans - 401(k), SEP, 
    Defined Contribution, Defined Benefit etc. This brings huge tax savings and a financially secure retirement.
    With the recent changes in tax laws, lot of creative strategies can be developed thereby maximizing the contribution for owners 
    and in some cases the deductions can be as much as several hundred thousands of dollars.
  image: /assets/img/retire_service.jpg

- type: Estate Planning
  description: One of the planning avenues that are often overlooked by many until it is too late is Estate Planning and in fact 
    can be the most cost-effective means of saving additional money for your heirs. Such planning goes well beyond an annual 
    gifting program, extending to the creation of family limited partnerships, trusts and charitable foundations, among many 
    other planning opportunities.
    We propose a comprehensive plan, using appropriate tools available, in conjunction with asset protection to reduce estate 
    and gift taxes to the greatest extent possible while still achieving various other goals that you may have.
    Our firm is staffed by a cadre of seasoned professionals who are highly qualified, and have spent years guiding clients to 
    manage their finances thus bridging the chasm between opportunity and reality. We provide both a comprehensive array of 
    resources and the personal touch of a trusted tax advisor. We look forward to an opportunity of working for you.
  image: /assets/img/estate_service.jpg
  
- type: Audit Services
  description: K.K Mehta CPA Associates PLLC is committed to compliance with all audit requirements and standards, and we 
    emphasize providing audit services that add value for our clients. Audit standards require auditors to be engaged by and 
    report directly to the Board of Directors and/or Audit Committee. This allows our professionals to consult on questions 
    concerning the audit without added costs.
    Our audits are further enhanced by partner accessibility – direct partner involvement in the field to supervise qualified 
    staff and consult with management during the audit process, audit efficiency – annual internal training sessions are 
    designed specifically for the financial institution team to ensure that the individuals who work on your audit are experts 
    and as a result, are efficient and effective.
    We are a Peer Reviewed Audit Firm and also members of NY State Society of CPA’s and PCAOB.
  image: /assets/img/audit_service.jpg

- type: Advisory Services
  description: Every year with new legislations the Congress adds numerous tax provisions to the already complex Internal 
    Revenue Code. Whether you are an Individual starting your career, having a corporation since years or nearing retirement 
    you must be thoroughly aware how complex our system of taxation is.
    It is virtually impossible for any individual or business to keep a track of all the new laws, their implications, numerous 
    tax planning opportunities to utilize or the tax pitfalls to avoid.
    That is where K. K. Mehta CPA Associates PLLC’s Tax Division steps in. We not only prepare your Individual, Corporation, 
    Partnerships, LLCs, Trust, Pension, Estate tax return, but also work with you round the year and look for every opportunity 
    to save your hard earned dollar. Additionally we also have interim planning sessions where we update ourselves of the 
    developments in your business and accordingly plan the tax incentives available to you at various levels.
  image: /assets/img/advisory_service.jpg